<?xml version="1.0" encoding="utf-8"?>
<Database Name="Fisharoo" Class="FisharooDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=Fisharoo;Integrated Security=True" SettingsObjectName="Fisharoo.FisharooCore.Properties.Settings" SettingsPropertyName="FisharooConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
</Database>