<%@ Page Language="C#" MasterPageFile="~/SiteMaster.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Fisharoo.FisharooWeb.Default" %>

<asp:Content ContentPlaceHolderID="Content" runat="server">
    <asp:Label ID="lblMsg" runat="server" ForeColor="Red"></asp:Label><br />
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras fermentum ipsum ut magna. Aenean vitae mi. Cras sollicitudin ornare erat. In hac habitasse platea dictumst. Aenean dolor metus, vulputate a, bibendum vel, laoreet nec, pede. Pellentesque quis odio. Etiam lorem dolor, rutrum ac, hendrerit vel, sollicitudin ac, orci. Morbi mauris velit, feugiat quis, semper id, auctor ut, metus. Aliquam nec odio sit amet nisl tempus sollicitudin. Duis nisl.
    <br /><br />
    Aliquam tristique augue placerat odio imperdiet bibendum. Pellentesque leo metus, molestie vel, iaculis nec, congue vitae, sem. Curabitur sollicitudin pede eget metus. Nullam aliquet rhoncus tortor. Etiam condimentum, neque sit amet vehicula feugiat, tellus leo feugiat eros, a tincidunt turpis felis sit amet nunc. Pellentesque lobortis est vel justo. Cras adipiscing lacus. Sed pede leo, lobortis ac, ultrices eu, mollis ut, justo. Duis nulla nulla, commodo ac, scelerisque sit amet, pellentesque in, odio. Nulla neque tellus, feugiat eu, volutpat id, tempor in, leo. Curabitur tincidunt. Sed quam. Nulla ipsum orci, accumsan tincidunt, scelerisque vitae, dapibus at, dolor. Ut dictum mollis nulla. Nulla posuere quam sed est. Maecenas fermentum sapien ut dolor. Duis metus orci, suscipit ac, sodales a, volutpat vitae, augue.
    <br /><br />
    Cras ornare nisl sit amet lacus. Vestibulum tincidunt arcu a enim. Suspendisse eget tellus nec orci sollicitudin posuere. Mauris fringilla. Sed nonummy nisi eu felis. Maecenas ac nisl id nisl accumsan bibendum. In ac odio. Suspendisse luctus mollis est. Nulla et velit. Etiam feugiat tortor nonummy neque. Fusce ut tellus. Aliquam erat volutpat. Sed vulputate bibendum massa. Etiam congue feugiat pede.
    <br /><br />
    In tristique adipiscing purus. Quisque posuere gravida nulla. Morbi velit diam, dapibus ut, rutrum at, consectetuer ac, risus. Pellentesque eros. Nullam risus. Vivamus tincidunt purus a turpis. Praesent aliquet. Donec nec nisi sed eros tempor consequat. Aenean et orci sed erat facilisis mollis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi scelerisque. Integer et sem in risus imperdiet pulvinar. Morbi diam. Sed tristique, dolor et euismod hendrerit, odio arcu consectetuer massa, sed elementum sapien lectus at magna. Curabitur semper mattis tellus. Ut urna risus, sodales ut, lacinia et, sollicitudin vitae, purus.
    <br /><br />
    Nullam massa arcu, hendrerit et, molestie vel, tempor at, urna. Etiam tellus neque, facilisis consectetuer, adipiscing eget, suscipit quis, elit. Nunc quam magna, interdum non, adipiscing vel, fringilla vitae, turpis. Suspendisse porta. Integer tempus cursus dui. Suspendisse eget lorem. Donec iaculis. Maecenas lacus diam, suscipit vel, tincidunt in, sollicitudin in, est. Vestibulum vestibulum ipsum et erat. Integer fringilla. Vestibulum eget odio ut sem fermentum volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin euismod. Nam ut sapien quis purus tempor imperdiet. Sed aliquam vestibulum odio. Phasellus hendrerit, turpis sit amet hendrerit cursus, ligula nisi congue sem, sed sodales purus erat vitae justo. Nulla facilisi.
</asp:Content>